repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      exclude: chronify/_vendor/.*
    # Run the formatter.
    - id: ruff-format
      exclude: chronify/_vendor/.*
